local data = {
	Rifle = {
		Damage = 24,
		FireRate = 0.1,
		MagazineSize = 30,
		ReserveAmmo = 120,
		ReloadTime = 1.8,
		Automatic = true,
		Spread = 1.2,
		Range = 650,
		RangeFalloff = {Start = 120, End = 650, MinScale = 0.75},
		HeadshotMultiplier = 1.6,
		MovementPenalty = 0.05,
		WeaponRole = "Assault",
		RecoilPattern = {0.7, -0.2, 0.65, 0.1, 0.8, -0.1, 0.6, 0.2},
		Pellets = 1,
	},
	Carbine = {
		Damage = 20,
		FireRate = 0.08,
		MagazineSize = 36,
		ReserveAmmo = 144,
		ReloadTime = 2.0,
		Automatic = true,
		Spread = 1.6,
		Range = 600,
		RangeFalloff = {Start = 100, End = 600, MinScale = 0.7},
		HeadshotMultiplier = 1.5,
		MovementPenalty = 0.04,
		WeaponRole = "Assault",
		RecoilPattern = {0.55, -0.15, 0.5, 0.12, 0.6, -0.08, 0.5, 0.1},
		Pellets = 1,
	},
	SMG = {
		Damage = 16,
		FireRate = 0.06,
		MagazineSize = 38,
		ReserveAmmo = 152,
		ReloadTime = 1.6,
		Automatic = true,
		Spread = 2.6,
		Range = 430,
		RangeFalloff = {Start = 70, End = 430, MinScale = 0.62},
		HeadshotMultiplier = 1.35,
		MovementPenalty = 0.02,
		WeaponRole = "SMG",
		RecoilPattern = {0.4, -0.35, 0.5, 0.28, 0.45, -0.3, 0.55, 0.22},
		Pellets = 1,
	},
	Pistol = {
		Damage = 20,
		FireRate = 0.22,
		MagazineSize = 12,
		ReserveAmmo = 60,
		ReloadTime = 1.4,
		Automatic = false,
		Spread = 0.8,
		Range = 500,
		RangeFalloff = {Start = 100, End = 500, MinScale = 0.72},
		HeadshotMultiplier = 1.7,
		MovementPenalty = 0.01,
		WeaponRole = "Pistol",
		RecoilPattern = {0.8, 0, 0.75, 0.05},
		Pellets = 1,
	},
	Sniper = {
		Damage = 80,
		FireRate = 1.1,
		MagazineSize = 5,
		ReserveAmmo = 25,
		ReloadTime = 2.5,
		Automatic = false,
		Spread = 0.2,
		Range = 1200,
		RangeFalloff = {Start = 400, End = 1200, MinScale = 0.88},
		HeadshotMultiplier = 2.0,
		MovementPenalty = 0.12,
		WeaponRole = "Sniper",
		RecoilPattern = {2.1, 0, 1.2, 0},
		Pellets = 1,
	},
	Shotgun = {
		Damage = 9,
		FireRate = 0.85,
		MagazineSize = 8,
		ReserveAmmo = 40,
		ReloadTime = 2.3,
		Automatic = false,
		Spread = 5.0,
		Range = 240,
		RangeFalloff = {Start = 25, End = 240, MinScale = 0.38},
		HeadshotMultiplier = 1.25,
		MovementPenalty = 0.08,
		WeaponRole = "Shotgun",
		RecoilPattern = {1.4, 0, 1.2, 0.05},
		Pellets = 8,
	},
	Knife = {
		Damage = 45,
		FireRate = 0.6,
		MagazineSize = 0,
		ReserveAmmo = 0,
		ReloadTime = 0,
		Automatic = false,
		Spread = 0,
		Range = 9,
		RangeFalloff = {Start = 0, End = 9, MinScale = 1},
		HeadshotMultiplier = 1,
		MovementPenalty = 0,
		WeaponRole = "Melee",
		RecoilPattern = {0, 0},
		Pellets = 1,
		IsMelee = true,
		HitCone = 40,
		LungeDistance = 0,
		BackstabMultiplier = 1.1,
	},
	LightKnife = {
		Damage = 30,
		FireRate = 0.38,
		MagazineSize = 0,
		ReserveAmmo = 0,
		ReloadTime = 0,
		Automatic = false,
		Spread = 0,
		Range = 8,
		RangeFalloff = {Start = 0, End = 8, MinScale = 1},
		HeadshotMultiplier = 1,
		MovementPenalty = 0,
		WeaponRole = "Melee",
		RecoilPattern = {0, 0},
		Pellets = 1,
		IsMelee = true,
		HitCone = 55,
		LungeDistance = 0.8,
		BackstabMultiplier = 1.35,
	},
	HeavyBlade = {
		Damage = 62,
		FireRate = 0.95,
		MagazineSize = 0,
		ReserveAmmo = 0,
		ReloadTime = 0,
		Automatic = false,
		Spread = 0,
		Range = 10,
		RangeFalloff = {Start = 0, End = 10, MinScale = 1},
		HeadshotMultiplier = 1,
		MovementPenalty = 0.02,
		WeaponRole = "Melee",
		RecoilPattern = {0, 0},
		Pellets = 1,
		IsMelee = true,
		HitCone = 48,
		LungeDistance = 2.5,
		BackstabMultiplier = 1.5,
	},
	Scythe = {
		Damage = 52,
		FireRate = 0.82,
		MagazineSize = 0,
		ReserveAmmo = 0,
		ReloadTime = 0,
		Automatic = false,
		Spread = 0,
		Range = 11,
		RangeFalloff = {Start = 0, End = 11, MinScale = 1},
		HeadshotMultiplier = 1,
		MovementPenalty = 0.01,
		WeaponRole = "Melee",
		RecoilPattern = {0, 0},
		Pellets = 1,
		IsMelee = true,
		HitCone = 80,
		LungeDistance = 1.2,
		BackstabMultiplier = 1.4,
	},
	Dagger = {
		Damage = 26,
		FireRate = 0.3,
		MagazineSize = 0,
		ReserveAmmo = 0,
		ReloadTime = 0,
		Automatic = false,
		Spread = 0,
		Range = 7,
		RangeFalloff = {Start = 0, End = 7, MinScale = 1},
		HeadshotMultiplier = 1,
		MovementPenalty = 0,
		WeaponRole = "Melee",
		RecoilPattern = {0, 0},
		Pellets = 1,
		IsMelee = true,
		HitCone = 45,
		LungeDistance = 1.4,
		BackstabMultiplier = 2.2,
	},
}

for name, weapon in pairs(data) do
	weapon.FireMode = weapon.FireMode or (weapon.Automatic and "Auto" or "Semi")
	weapon.BaseSpread = weapon.BaseSpread or weapon.Spread or 0
	weapon.MoveSpread = weapon.MoveSpread or 1.1
	weapon.AirSpread = weapon.AirSpread or 1.8
	weapon.RecoilSpread = weapon.RecoilSpread or 0.32
	weapon.RecoilRecoverySpeed = weapon.RecoilRecoverySpeed or 6
	weapon.VerticalRecoil = weapon.VerticalRecoil or math.max(0.28, (weapon.Spread or 1) * 0.32)
	weapon.HorizontalRecoil = weapon.HorizontalRecoil or math.max(0.08, (weapon.Spread or 1) * 0.12)
	weapon.SoundProfile = weapon.SoundProfile or name
	weapon.ViewmodelReference = weapon.ViewmodelReference or name
end

return data
